spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RapiSolverOpen
    username: postgres
    password: diego2009
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true 
